name: Soroban Tools e2e

on:
  push:
    branches: [main, release/**]
  pull_request:

jobs:
  integration:
    name: System tests
    strategy:
      matrix:
        scenario-filter: ["^TestDappDevelop$/^.*$"]
    runs-on: ubuntu-latest
    env:
      TOOLS_REF: ${{ github.ref }}
      SYSTEM_TEST_GIT_REF: refs/pull/23/head
      SYSTEM_TEST_CORE_GIT_REF: master
      SYSTEM_TEST_CORE_COMPILE_CONFIGURE_FLAGS: "--disable-tests --enable-next-protocol-version-unsafe-for-production"
      SYSTEM_TEST_RUST_TOOLCHAIN_VERSION: stable
      SYSTEM_TEST_QUICKSTART_GIT_REF: master
      SYSTEM_TEST_VERBOSE_OUTPUT: "true"
      SYSTEM_TEST_SOROBAN_EXAMPLES_GIT_HASH: main
      SYSTEM_TEST_SOROBAN_EXAMPLES_GIT_REPO: "https://github.com/stellar/soroban-examples.git"
    steps:
      - uses: actions/checkout@v3
        with:
          repository: stellar/system-test
          ref: ${{ env.SYSTEM_TEST_GIT_REF }}
      - uses: stellar/actions/rust-cache@main 
      - name: Run system test scenarios
        run: |
          make CORE_GIT_REF=$SYSTEM_TEST_CORE_GIT_REF \
              CORE_COMPILE_CONFIGURE_FLAGS="$SYSTEM_TEST_CORE_COMPILE_CONFIGURE_FLAGS" \
              SOROBAN_RPC_GIT_REF=$TOOLS_REF \
              RUST_TOOLCHAIN_VERSION=$SYSTEM_TEST_RUST_TOOLCHAIN_VERSION \
              SOROBAN_CLI_GIT_REF=$TOOLS_REF \
              QUICKSTART_GIT_REF=$SYSTEM_TEST_QUICKSTART_GIT_REF \
              build

          docker run --rm -t --name e2e_test stellar/system-test:dev \
          --VerboseOutput $SYSTEM_TEST_VERBOSE_OUTPUT  \
          --TestFilter "${{ matrix.scenario-filter }}" 
